name: Postman API Tests

on:
  push:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection
        run: |
          newman run postman/Inventory_API_Testing.postman_collection.json \
          -e postman/Inventory_API_Testing_env.postman_environment.json